{% set name = "rocminfo" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/rocminfo/archive/rocm-{{ version }}.tar.gz
  sha256: e616d364a48de18eaee661bdce999d095086905f49777663ca99312f40a63da1

build:
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - {{ cdt('pciutils-devel') }}
    - cmake
    - make
  host:
    - numactl
    - rocr-runtime {{ version }}
  run:
    - rocr-runtime {{ version }}
    - libnuma

test:
  commands:
    # Can't run this command without an AMD GPU
    - test -f $PREFIX/bin/rocminfo
    - test -f $PREFIX/bin/rocm_agent_enumerator
    - msg=$($PREFIX/bin/rocminfo 2>&1; test $? -eq 1) && test "$msg" = "$(echo -e '\033[31mROCk module is NOT loaded, possibly no GPU devices\033[0m')"   # [CI]

about:
  home: https://github.com/ROCm/rocminfo
  license: NCSA
  license_family: MIT
  license_file: License.txt
  summary: 'ROCm Application for Reporting System Info'

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
