{% set name = "rocminfo" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/rocminfo/archive/roc-{{ version }}.tar.gz
  sha256: 5ee73ff3f837946251b89a4f35a7a27a68ed0c2c258745aa8e6acb032ef20e72

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('numactl-devel') }}
    - {{ cdt('pciutils-devel') }}
  host:
    - rocr-runtime {{ version }}
    - elfutils
  run:
    - rocr-runtime {{ version }}
    - {{ pin_compatible("elfutils", max_pin="x.x") }}

test:
  commands:
    # Can't run this command without an AMD GPU
    - test -f $PREFIX/bin/rocminfo

about:
  home: https://github.com/RadeonOpenCompute/rocminfo
  license: NCSA
  license_family: MIT
  license_file: License.txt
  summary: 'ROCm Application for Reporting System Info'

extra:
  recipe-maintainers:
    - isuruf
